apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: fluentbit-test
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    #@INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name tail
        Tag     nw-social-user-qa
        Parser  json
        Path    /var/log/containers/nw-social-user-qa*.log
        DB  /var/log/flb_kube.db
        Refresh_Interval 5
        Mem_Buf_Limit 100MB
        Buffer_Chunk_Size 128k
        Buffer_Max_Size 4096k
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Tag     nw-social-scheduler-qa
        Parser  json
        Path    /var/log/containers/nw-social-scheduler-qa*.log
        DB  /var/log/flb_kube.db
        Refresh_Interval 5
        Mem_Buf_Limit 100MB
        Buffer_Chunk_Size 128k
        Buffer_Max_Size 4096k
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Tag     nw-social-reader-qa
        Parser  json
        Path    /var/log/containers/nw-social-reader-qa*.log
        DB  /var/log/flb_kube.db
        Refresh_Interval 5
        Mem_Buf_Limit 100MB
        Buffer_Chunk_Size 128k
        Buffer_Max_Size 4096k
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Tag     nw-social-post-qa
        Parser  json
        Path    /var/log/containers/nw-social-post-qa*.log
        DB  /var/log/flb_kube.db
        Refresh_Interval 5
        Mem_Buf_Limit 100MB
        Buffer_Chunk_Size 128k
        Buffer_Max_Size 4096k
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Tag     nw-social-notification-qa
        Parser  json
        Path    /var/log/containers/nw-social-notification-qa*.log
        DB  /var/log/flb_kube.db
        Refresh_Interval 5
        Mem_Buf_Limit 100MB
        Buffer_Chunk_Size 128k
        Buffer_Max_Size 4096k
        Skip_Long_Lines On

    [INPUT]
        Name tail
        Tag     nw-social-migration-qa
        Parser  json
        Path    /var/log/containers/nw-social-migration-qa*.log
        DB  /var/log/flb_kube.db
        Refresh_Interval 5
        Mem_Buf_Limit 100MB
        Buffer_Chunk_Size 128k
        Buffer_Max_Size 4096k
        Skip_Long_Lines On


  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           Off
        K8S-Logging.Parser  On

  output-elasticsearch.conf: |
    [OUTPUT]
        Name es
        Match nw-social-user-qa
        Host 192.168.1.143
        Port 9200
        Index nw-social-user-qa
        Logstash_Format true
        Logstash_Prefix nw-social-user-qa
        Type nw-social-user-qa
        Retry_Limit 1

    [OUTPUT]
        Name es
        Match nw-social-scheduler-qa
        Host 192.168.1.143
        Port 9200
        Index nw-social-scheduler-qa
        Logstash_Format true
        Logstash_Prefix nw-social-scheduler-qa
        Type nw-social-scheduler-qa
        Retry_Limit 1

    [OUTPUT]
        Name es
        Match nw-social-reader-qa
        Host 192.168.1.143
        Port 9200
        Index nw-social-reader-qa
        Logstash_Format true
        Logstash_Prefix nw-social-reader-qa
        Type nw-social-reader-qa
        Retry_Limit 1

    [OUTPUT]
        Name es
        Match nw-social-post-qa
        Host 192.168.1.143
        Port 9200
        Index nw-social-post-qa
        Logstash_Format true
        Logstash_Prefix nw-social-post-qa
        Type nw-social-post-qa
        Retry_Limit 1

    [OUTPUT]
        Name es
        Match nw-social-notification-qa
        Host 192.168.1.143
        Port 9200
        Index nw-social-notification-qa
        Logstash_Format true
        Logstash_Prefix nw-social-notification-qa
        Type nw-social-notification-qa
        Retry_Limit 1

    [OUTPUT]
        Name es
        Match nw-social-migration-qa
        Host 192.168.1.143
        Port 9200
        Index nw-social-migration-qa
        Logstash_Format true
        Logstash_Prefix nw-social-migration-qa
        Type nw-social-migration-qa
        Retry_Limit 1


  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

